spring:
  application:
    name: spartaeats
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:spartaeats}?currentSchema=public
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

server:
  port: ${PORT:8080}

springdoc:
  swagger-ui:
    path: /swagger

# JWT 설정 (공통)
jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration-time: ${JWT_EXPIRATION_TIME:3600000}  # 기본 1시간