spring:
  application:
    name: spartaeats
  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:spartaeats}?currentSchema=public
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

server:
  port: ${PORT:8080}

springdoc:
  swagger-ui:
    path: /swagger