spring:
  application:
    name: spartaeats
  config:
    import: optional:file:.env[.properties]
  profiles:
    default: dev

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:spartaeats}?currentSchema=public
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

server:
  port: ${PORT:8080}

springdoc:
  swagger-ui:
    path: /swagger

# JWT 설정 (공통)
jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration-time: ${JWT_EXPIRATION_TIME:3600000}  # 기본 1시간

# 개발 과정에서는 dummy-key-for-test 사용중
kakao:
  api-key: ${KAKAO_API_KEY:dummy-key-for-test}
tmap:
  api-key: ${TMAP_API_KEY:dummy-key-for-test}
google:
  api:
    key: ${GOOGLE_API_KEY:dummy-key-for-test}


toss:
  base-url: https://api.tosspayments.com
  secret-key: ${TOSS_SECRET_KEY}
  client-key: ${TOSS_CLIENT_KEY:}
  mock-enabled: ${TOSS_MOCK:true} # 테스트/모의 전환용